[consul]
host = "127.0.0.1:8500"
service_name = "JudgeCore"
service_id = "JudgeCore-1"

[rabbitmq]
host = "amqp://guest:guest@127.0.0.1:5672/"
exchange = "judge.submission.exchange"
main_queue = "judge.submission.main"
prefetch = 1

[backend_rebuild]
base_url = "http://127.0.0.1:8082/api/v1"
judge_token = ""

[server]
host = "127.0.0.1"
port = 8082
enable_https = false
cert_path = "./certificate/fullchain.pem"
key_path = "./certificate/privkey.key"

[sandbox]
memory = 2147483648
nano_cpus = 0.5
cpu_shares = 1024
max_concurrent = 5

[database]
type = "mysql"
host = "localhost"
port = 3306
name = "FeasOJ"
user = "root"
password = "password"
ssl_mode = "disable"
